package com.cts.app.parser.util;

public enum ErrorEnum {

	TITLE_INVALID, MAKE_INVALID, MODEL_INVALID, YEAR_INVALID, ZIP_INVALID, PRICE_INVALID, VIN_INVALID, MILEAGE_INVALID, DESCRIPTION_INVALID, IMAGES_INVALID

}
